### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by laeubi** [AnIML/schemas#11]
https://www.animl.org currently only times out but do not deliver any content.

If hosting an own website is currently not desired, it would be good if it redirects to
https://github.com/AnIML

and an organization readme is created so users can contribute data there more easily:
https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#organization-profile-readmes

**Comment by burkhardschaefer** [comment]
The site is moving to a different hosting account as part of the animl.org transition. Should be back up in the next few days.

**Comment by Mailaender** [comment]
http://techniques.animl.org/ is still down:
* http://techniques.animl.org/uv-vis/current/uv-vis.atdd
* http://techniques.animl.org/chromatography/current/chromatography.atdd

both HTTP and HTTPS
