### ISSUE TITLE
.animl file extension should be documented

### ISSUE THREAD

**Issue by Mailaender** [AnIML/schemas#7]
I think the file extension as discussed in https://github.com/AnIML/schemas/issues/4#issuecomment-822627281 should be specified as thirdparty tools use the generic `*.xml` ending which will cause problems. See https://sciencesolutions.wiley.com/wp-content/uploads/2021/08/210421-Wiley_KnowItAll_Software_File_Format_Datasheet.pdf

**Comment by burkhardschaefer** [comment]
It is documented in the ASTM standard, along with the MIME type to use.
